/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.permify.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.permify.model.DataBundle;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BundleWriteRequest is used to request the writing of a bundle. It contains the tenant_id to identify the tenant and the Bundles object.
 */
@JsonPropertyOrder({
  BundleWriteRequest.JSON_PROPERTY_BUNDLES
})
@JsonTypeName("bundle_write_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-07-19T12:59:35.606772+03:00[Europe/Istanbul]", comments = "Generator version: 7.7.0")
public class BundleWriteRequest {
  public static final String JSON_PROPERTY_BUNDLES = "bundles";
  private List<DataBundle> bundles = new ArrayList<>();

  public BundleWriteRequest() {
  }

  public BundleWriteRequest bundles(List<DataBundle> bundles) {
    
    this.bundles = bundles;
    return this;
  }

  public BundleWriteRequest addBundlesItem(DataBundle bundlesItem) {
    if (this.bundles == null) {
      this.bundles = new ArrayList<>();
    }
    this.bundles.add(bundlesItem);
    return this;
  }

  /**
   * Contains the bundle data to be written.
   * @return bundles
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUNDLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DataBundle> getBundles() {
    return bundles;
  }


  @JsonProperty(JSON_PROPERTY_BUNDLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBundles(List<DataBundle> bundles) {
    this.bundles = bundles;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BundleWriteRequest bundleWriteRequest = (BundleWriteRequest) o;
    return Objects.equals(this.bundles, bundleWriteRequest.bundles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BundleWriteRequest {\n");
    sb.append("    bundles: ").append(toIndentedString(bundles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

