/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.permify.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import org.permify.model.Expr;
import org.permify.model.SourceInfo;
import org.permify.model.V1alpha1Reference;
import org.permify.model.V1alpha1Type;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CheckedExpr
 */
class CheckedExprTest {
    private final CheckedExpr model = new CheckedExpr();

    /**
     * Model tests for CheckedExpr
     */
    @Test
    void testCheckedExpr() {
        // TODO: test CheckedExpr
    }

    /**
     * Test the property 'referenceMap'
     */
    @Test
    void referenceMapTest() {
        // TODO: test referenceMap
    }

    /**
     * Test the property 'typeMap'
     */
    @Test
    void typeMapTest() {
        // TODO: test typeMap
    }

    /**
     * Test the property 'sourceInfo'
     */
    @Test
    void sourceInfoTest() {
        // TODO: test sourceInfo
    }

    /**
     * Test the property 'exprVersion'
     */
    @Test
    void exprVersionTest() {
        // TODO: test exprVersion
    }

    /**
     * Test the property 'expr'
     */
    @Test
    void exprTest() {
        // TODO: test expr
    }

}
