/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.permify.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DataWriteRequestMetadata
 */
class DataWriteRequestMetadataTest {
    private final DataWriteRequestMetadata model = new DataWriteRequestMetadata();

    /**
     * Model tests for DataWriteRequestMetadata
     */
    @Test
    void testDataWriteRequestMetadata() {
        // TODO: test DataWriteRequestMetadata
    }

    /**
     * Test the property 'schemaVersion'
     */
    @Test
    void schemaVersionTest() {
        // TODO: test schemaVersion
    }

}
