/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v0.9.9
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.permify.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.permify.model.PermissionLookupEntityStreamResponse;
import org.permify.model.Status;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for StreamResultOfPermissionLookupEntityStreamResponse
 */
class StreamResultOfPermissionLookupEntityStreamResponseTest {
    private final StreamResultOfPermissionLookupEntityStreamResponse model = new StreamResultOfPermissionLookupEntityStreamResponse();

    /**
     * Model tests for StreamResultOfPermissionLookupEntityStreamResponse
     */
    @Test
    void testStreamResultOfPermissionLookupEntityStreamResponse() {
        // TODO: test StreamResultOfPermissionLookupEntityStreamResponse
    }

    /**
     * Test the property 'result'
     */
    @Test
    void resultTest() {
        // TODO: test result
    }

    /**
     * Test the property 'error'
     */
    @Test
    void errorTest() {
        // TODO: test error
    }

}
