/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.4.4
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import co.permify.sdk.model.Leaf;
import co.permify.sdk.model.Rewrite;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Child
 */
public class ChildTest {
    private final Child model = new Child();

    /**
     * Model tests for Child
     */
    @Test
    public void testChild() {
        // TODO: test Child
    }

    /**
     * Test the property 'leaf'
     */
    @Test
    public void leafTest() {
        // TODO: test leaf
    }

    /**
     * Test the property 'rewrite'
     */
    @Test
    public void rewriteTest() {
        // TODO: test rewrite
    }

}
