/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.4.3
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import co.permify.sdk.model.Attribute;
import co.permify.sdk.model.DataChangeOperation;
import co.permify.sdk.model.Tuple;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for DataChange
 */
public class DataChangeTest {
    private final DataChange model = new DataChange();

    /**
     * Model tests for DataChange
     */
    @Test
    public void testDataChange() {
        // TODO: test DataChange
    }

    /**
     * Test the property 'operation'
     */
    @Test
    public void operationTest() {
        // TODO: test operation
    }

    /**
     * Test the property 'tuple'
     */
    @Test
    public void tupleTest() {
        // TODO: test tuple
    }

    /**
     * Test the property 'attribute'
     */
    @Test
    public void attributeTest() {
        // TODO: test attribute
    }

}
