/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import co.permify.sdk.model.Comprehension;
import co.permify.sdk.model.Constant;
import co.permify.sdk.model.CreateList;
import co.permify.sdk.model.CreateStruct;
import co.permify.sdk.model.ExprCall;
import co.permify.sdk.model.Ident;
import co.permify.sdk.model.Select;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for Expr
 */
public class ExprTest {
    private final Expr model = new Expr();

    /**
     * Model tests for Expr
     */
    @Test
    public void testExpr() {
        // TODO: test Expr
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'constExpr'
     */
    @Test
    public void constExprTest() {
        // TODO: test constExpr
    }

    /**
     * Test the property 'identExpr'
     */
    @Test
    public void identExprTest() {
        // TODO: test identExpr
    }

    /**
     * Test the property 'selectExpr'
     */
    @Test
    public void selectExprTest() {
        // TODO: test selectExpr
    }

    /**
     * Test the property 'callExpr'
     */
    @Test
    public void callExprTest() {
        // TODO: test callExpr
    }

    /**
     * Test the property 'listExpr'
     */
    @Test
    public void listExprTest() {
        // TODO: test listExpr
    }

    /**
     * Test the property 'structExpr'
     */
    @Test
    public void structExprTest() {
        // TODO: test structExpr
    }

    /**
     * Test the property 'comprehensionExpr'
     */
    @Test
    public void comprehensionExprTest() {
        // TODO: test comprehensionExpr
    }

}
