/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.4.3
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import co.permify.sdk.model.V1Expand;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for PermissionExpandResponse
 */
public class PermissionExpandResponseTest {
    private final PermissionExpandResponse model = new PermissionExpandResponse();

    /**
     * Model tests for PermissionExpandResponse
     */
    @Test
    public void testPermissionExpandResponse() {
        // TODO: test PermissionExpandResponse
    }

    /**
     * Test the property 'tree'
     */
    @Test
    public void treeTest() {
        // TODO: test tree
    }

}
