/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.0.3
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import co.permify.sdk.model.Context;
import co.permify.sdk.model.Entity;
import co.permify.sdk.model.PermissionSubjectPermissionRequestMetadata;
import co.permify.sdk.model.Subject;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubjectPermissionBody
 */
class SubjectPermissionBodyTest {
    private final SubjectPermissionBody model = new SubjectPermissionBody();

    /**
     * Model tests for SubjectPermissionBody
     */
    @Test
    void testSubjectPermissionBody() {
        // TODO: test SubjectPermissionBody
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'entity'
     */
    @Test
    void entityTest() {
        // TODO: test entity
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'context'
     */
    @Test
    void contextTest() {
        // TODO: test context
    }

}
