/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.0.3
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TenantListRequest
 */
class TenantListRequestTest {
    private final TenantListRequest model = new TenantListRequest();

    /**
     * Model tests for TenantListRequest
     */
    @Test
    void testTenantListRequest() {
        // TODO: test TenantListRequest
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'continuousToken'
     */
    @Test
    void continuousTokenTest() {
        // TODO: test continuousToken
    }

}
