/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.5.4
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import co.permify.sdk.model.Tenant;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TenantListResponse
 */
public class TenantListResponseTest {
    private final TenantListResponse model = new TenantListResponse();

    /**
     * Model tests for TenantListResponse
     */
    @Test
    public void testTenantListResponse() {
        // TODO: test TenantListResponse
    }

    /**
     * Test the property 'tenants'
     */
    @Test
    public void tenantsTest() {
        // TODO: test tenants
    }

    /**
     * Test the property 'continuousToken'
     */
    @Test
    public void continuousTokenTest() {
        // TODO: test continuousToken
    }

}
