// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base/v1/service.proto
// Protobuf Java Version: 4.27.2

package org.permify.grpc;

/**
 * <pre>
 * DataDeleteRequest defines the structure of a request to delete data.
 * It includes the tenant_id and filters for selecting tuples and attributes to be deleted.
 * </pre>
 *
 * Protobuf type {@code base.v1.DataDeleteRequest}
 */
public final class DataDeleteRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:base.v1.DataDeleteRequest)
    DataDeleteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      DataDeleteRequest.class.getName());
  }
  // Use DataDeleteRequest.newBuilder() to construct.
  private DataDeleteRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private DataDeleteRequest() {
    tenantId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.permify.grpc.ServiceProto.internal_static_base_v1_DataDeleteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.permify.grpc.ServiceProto.internal_static_base_v1_DataDeleteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.permify.grpc.DataDeleteRequest.class, org.permify.grpc.DataDeleteRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TENANT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tenantId_ = "";
  /**
   * <pre>
   * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
   * </pre>
   *
   * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TUPLE_FILTER_FIELD_NUMBER = 2;
  private org.permify.grpc.TupleFilter tupleFilter_;
  /**
   * <pre>
   * tuple_filter specifies the criteria used to select the tuples that should be deleted.
   * </pre>
   *
   * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
   * @return Whether the tupleFilter field is set.
   */
  @java.lang.Override
  public boolean hasTupleFilter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * tuple_filter specifies the criteria used to select the tuples that should be deleted.
   * </pre>
   *
   * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
   * @return The tupleFilter.
   */
  @java.lang.Override
  public org.permify.grpc.TupleFilter getTupleFilter() {
    return tupleFilter_ == null ? org.permify.grpc.TupleFilter.getDefaultInstance() : tupleFilter_;
  }
  /**
   * <pre>
   * tuple_filter specifies the criteria used to select the tuples that should be deleted.
   * </pre>
   *
   * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.permify.grpc.TupleFilterOrBuilder getTupleFilterOrBuilder() {
    return tupleFilter_ == null ? org.permify.grpc.TupleFilter.getDefaultInstance() : tupleFilter_;
  }

  public static final int ATTRIBUTE_FILTER_FIELD_NUMBER = 3;
  private org.permify.grpc.AttributeFilter attributeFilter_;
  /**
   * <pre>
   * attribute_filter specifies the criteria used to select the attributes that should be deleted.
   * </pre>
   *
   * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
   * @return Whether the attributeFilter field is set.
   */
  @java.lang.Override
  public boolean hasAttributeFilter() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * attribute_filter specifies the criteria used to select the attributes that should be deleted.
   * </pre>
   *
   * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
   * @return The attributeFilter.
   */
  @java.lang.Override
  public org.permify.grpc.AttributeFilter getAttributeFilter() {
    return attributeFilter_ == null ? org.permify.grpc.AttributeFilter.getDefaultInstance() : attributeFilter_;
  }
  /**
   * <pre>
   * attribute_filter specifies the criteria used to select the attributes that should be deleted.
   * </pre>
   *
   * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
   */
  @java.lang.Override
  public org.permify.grpc.AttributeFilterOrBuilder getAttributeFilterOrBuilder() {
    return attributeFilter_ == null ? org.permify.grpc.AttributeFilter.getDefaultInstance() : attributeFilter_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, tenantId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTupleFilter());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getAttributeFilter());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, tenantId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTupleFilter());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAttributeFilter());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.permify.grpc.DataDeleteRequest)) {
      return super.equals(obj);
    }
    org.permify.grpc.DataDeleteRequest other = (org.permify.grpc.DataDeleteRequest) obj;

    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (hasTupleFilter() != other.hasTupleFilter()) return false;
    if (hasTupleFilter()) {
      if (!getTupleFilter()
          .equals(other.getTupleFilter())) return false;
    }
    if (hasAttributeFilter() != other.hasAttributeFilter()) return false;
    if (hasAttributeFilter()) {
      if (!getAttributeFilter()
          .equals(other.getAttributeFilter())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TENANT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    if (hasTupleFilter()) {
      hash = (37 * hash) + TUPLE_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getTupleFilter().hashCode();
    }
    if (hasAttributeFilter()) {
      hash = (37 * hash) + ATTRIBUTE_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeFilter().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.permify.grpc.DataDeleteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.permify.grpc.DataDeleteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.permify.grpc.DataDeleteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.DataDeleteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.permify.grpc.DataDeleteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DataDeleteRequest defines the structure of a request to delete data.
   * It includes the tenant_id and filters for selecting tuples and attributes to be deleted.
   * </pre>
   *
   * Protobuf type {@code base.v1.DataDeleteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:base.v1.DataDeleteRequest)
      org.permify.grpc.DataDeleteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_DataDeleteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_DataDeleteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.permify.grpc.DataDeleteRequest.class, org.permify.grpc.DataDeleteRequest.Builder.class);
    }

    // Construct using org.permify.grpc.DataDeleteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTupleFilterFieldBuilder();
        getAttributeFilterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tenantId_ = "";
      tupleFilter_ = null;
      if (tupleFilterBuilder_ != null) {
        tupleFilterBuilder_.dispose();
        tupleFilterBuilder_ = null;
      }
      attributeFilter_ = null;
      if (attributeFilterBuilder_ != null) {
        attributeFilterBuilder_.dispose();
        attributeFilterBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_DataDeleteRequest_descriptor;
    }

    @java.lang.Override
    public org.permify.grpc.DataDeleteRequest getDefaultInstanceForType() {
      return org.permify.grpc.DataDeleteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.permify.grpc.DataDeleteRequest build() {
      org.permify.grpc.DataDeleteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.permify.grpc.DataDeleteRequest buildPartial() {
      org.permify.grpc.DataDeleteRequest result = new org.permify.grpc.DataDeleteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.permify.grpc.DataDeleteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tenantId_ = tenantId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tupleFilter_ = tupleFilterBuilder_ == null
            ? tupleFilter_
            : tupleFilterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.attributeFilter_ = attributeFilterBuilder_ == null
            ? attributeFilter_
            : attributeFilterBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.permify.grpc.DataDeleteRequest) {
        return mergeFrom((org.permify.grpc.DataDeleteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.permify.grpc.DataDeleteRequest other) {
      if (other == org.permify.grpc.DataDeleteRequest.getDefaultInstance()) return this;
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTupleFilter()) {
        mergeTupleFilter(other.getTupleFilter());
      }
      if (other.hasAttributeFilter()) {
        mergeAttributeFilter(other.getAttributeFilter());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tenantId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTupleFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getAttributeFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      tenantId_ = getDefaultInstance().getTenantId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tenant_id represents the unique identifier of the tenant from which the data will be deleted.
     * </pre>
     *
     * <code>string tenant_id = 1 [json_name = "tenant_id", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tenantId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private org.permify.grpc.TupleFilter tupleFilter_;
    private com.google.protobuf.SingleFieldBuilder<
        org.permify.grpc.TupleFilter, org.permify.grpc.TupleFilter.Builder, org.permify.grpc.TupleFilterOrBuilder> tupleFilterBuilder_;
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     * @return Whether the tupleFilter field is set.
     */
    public boolean hasTupleFilter() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     * @return The tupleFilter.
     */
    public org.permify.grpc.TupleFilter getTupleFilter() {
      if (tupleFilterBuilder_ == null) {
        return tupleFilter_ == null ? org.permify.grpc.TupleFilter.getDefaultInstance() : tupleFilter_;
      } else {
        return tupleFilterBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    public Builder setTupleFilter(org.permify.grpc.TupleFilter value) {
      if (tupleFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tupleFilter_ = value;
      } else {
        tupleFilterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    public Builder setTupleFilter(
        org.permify.grpc.TupleFilter.Builder builderForValue) {
      if (tupleFilterBuilder_ == null) {
        tupleFilter_ = builderForValue.build();
      } else {
        tupleFilterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    public Builder mergeTupleFilter(org.permify.grpc.TupleFilter value) {
      if (tupleFilterBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          tupleFilter_ != null &&
          tupleFilter_ != org.permify.grpc.TupleFilter.getDefaultInstance()) {
          getTupleFilterBuilder().mergeFrom(value);
        } else {
          tupleFilter_ = value;
        }
      } else {
        tupleFilterBuilder_.mergeFrom(value);
      }
      if (tupleFilter_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    public Builder clearTupleFilter() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tupleFilter_ = null;
      if (tupleFilterBuilder_ != null) {
        tupleFilterBuilder_.dispose();
        tupleFilterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    public org.permify.grpc.TupleFilter.Builder getTupleFilterBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTupleFilterFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    public org.permify.grpc.TupleFilterOrBuilder getTupleFilterOrBuilder() {
      if (tupleFilterBuilder_ != null) {
        return tupleFilterBuilder_.getMessageOrBuilder();
      } else {
        return tupleFilter_ == null ?
            org.permify.grpc.TupleFilter.getDefaultInstance() : tupleFilter_;
      }
    }
    /**
     * <pre>
     * tuple_filter specifies the criteria used to select the tuples that should be deleted.
     * </pre>
     *
     * <code>.base.v1.TupleFilter tuple_filter = 2 [json_name = "tuple_filter", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.permify.grpc.TupleFilter, org.permify.grpc.TupleFilter.Builder, org.permify.grpc.TupleFilterOrBuilder> 
        getTupleFilterFieldBuilder() {
      if (tupleFilterBuilder_ == null) {
        tupleFilterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.permify.grpc.TupleFilter, org.permify.grpc.TupleFilter.Builder, org.permify.grpc.TupleFilterOrBuilder>(
                getTupleFilter(),
                getParentForChildren(),
                isClean());
        tupleFilter_ = null;
      }
      return tupleFilterBuilder_;
    }

    private org.permify.grpc.AttributeFilter attributeFilter_;
    private com.google.protobuf.SingleFieldBuilder<
        org.permify.grpc.AttributeFilter, org.permify.grpc.AttributeFilter.Builder, org.permify.grpc.AttributeFilterOrBuilder> attributeFilterBuilder_;
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     * @return Whether the attributeFilter field is set.
     */
    public boolean hasAttributeFilter() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     * @return The attributeFilter.
     */
    public org.permify.grpc.AttributeFilter getAttributeFilter() {
      if (attributeFilterBuilder_ == null) {
        return attributeFilter_ == null ? org.permify.grpc.AttributeFilter.getDefaultInstance() : attributeFilter_;
      } else {
        return attributeFilterBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    public Builder setAttributeFilter(org.permify.grpc.AttributeFilter value) {
      if (attributeFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        attributeFilter_ = value;
      } else {
        attributeFilterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    public Builder setAttributeFilter(
        org.permify.grpc.AttributeFilter.Builder builderForValue) {
      if (attributeFilterBuilder_ == null) {
        attributeFilter_ = builderForValue.build();
      } else {
        attributeFilterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    public Builder mergeAttributeFilter(org.permify.grpc.AttributeFilter value) {
      if (attributeFilterBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          attributeFilter_ != null &&
          attributeFilter_ != org.permify.grpc.AttributeFilter.getDefaultInstance()) {
          getAttributeFilterBuilder().mergeFrom(value);
        } else {
          attributeFilter_ = value;
        }
      } else {
        attributeFilterBuilder_.mergeFrom(value);
      }
      if (attributeFilter_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    public Builder clearAttributeFilter() {
      bitField0_ = (bitField0_ & ~0x00000004);
      attributeFilter_ = null;
      if (attributeFilterBuilder_ != null) {
        attributeFilterBuilder_.dispose();
        attributeFilterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    public org.permify.grpc.AttributeFilter.Builder getAttributeFilterBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getAttributeFilterFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    public org.permify.grpc.AttributeFilterOrBuilder getAttributeFilterOrBuilder() {
      if (attributeFilterBuilder_ != null) {
        return attributeFilterBuilder_.getMessageOrBuilder();
      } else {
        return attributeFilter_ == null ?
            org.permify.grpc.AttributeFilter.getDefaultInstance() : attributeFilter_;
      }
    }
    /**
     * <pre>
     * attribute_filter specifies the criteria used to select the attributes that should be deleted.
     * </pre>
     *
     * <code>.base.v1.AttributeFilter attribute_filter = 3 [json_name = "attribute_filter", (.validate.rules) = { ... }</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.permify.grpc.AttributeFilter, org.permify.grpc.AttributeFilter.Builder, org.permify.grpc.AttributeFilterOrBuilder> 
        getAttributeFilterFieldBuilder() {
      if (attributeFilterBuilder_ == null) {
        attributeFilterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.permify.grpc.AttributeFilter, org.permify.grpc.AttributeFilter.Builder, org.permify.grpc.AttributeFilterOrBuilder>(
                getAttributeFilter(),
                getParentForChildren(),
                isClean());
        attributeFilter_ = null;
      }
      return attributeFilterBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:base.v1.DataDeleteRequest)
  }

  // @@protoc_insertion_point(class_scope:base.v1.DataDeleteRequest)
  private static final org.permify.grpc.DataDeleteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.permify.grpc.DataDeleteRequest();
  }

  public static org.permify.grpc.DataDeleteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataDeleteRequest>
      PARSER = new com.google.protobuf.AbstractParser<DataDeleteRequest>() {
    @java.lang.Override
    public DataDeleteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataDeleteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataDeleteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.permify.grpc.DataDeleteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

