// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base/v1/base.proto
// Protobuf Java Version: 4.27.2

package org.permify.grpc;

/**
 * <pre>
 * Partials contains the write, update and delete definitions
 * </pre>
 *
 * Protobuf type {@code base.v1.Partials}
 */
public final class Partials extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:base.v1.Partials)
    PartialsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Partials.class.getName());
  }
  // Use Partials.newBuilder() to construct.
  private Partials(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Partials() {
    write_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    delete_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    update_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.permify.grpc.BaseProto.internal_static_base_v1_Partials_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.permify.grpc.BaseProto.internal_static_base_v1_Partials_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.permify.grpc.Partials.class, org.permify.grpc.Partials.Builder.class);
  }

  public static final int WRITE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList write_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string write = 1 [json_name = "write"];</code>
   * @return A list containing the write.
   */
  public com.google.protobuf.ProtocolStringList
      getWriteList() {
    return write_;
  }
  /**
   * <code>repeated string write = 1 [json_name = "write"];</code>
   * @return The count of write.
   */
  public int getWriteCount() {
    return write_.size();
  }
  /**
   * <code>repeated string write = 1 [json_name = "write"];</code>
   * @param index The index of the element to return.
   * @return The write at the given index.
   */
  public java.lang.String getWrite(int index) {
    return write_.get(index);
  }
  /**
   * <code>repeated string write = 1 [json_name = "write"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the write at the given index.
   */
  public com.google.protobuf.ByteString
      getWriteBytes(int index) {
    return write_.getByteString(index);
  }

  public static final int DELETE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList delete_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string delete = 2 [json_name = "delete"];</code>
   * @return A list containing the delete.
   */
  public com.google.protobuf.ProtocolStringList
      getDeleteList() {
    return delete_;
  }
  /**
   * <code>repeated string delete = 2 [json_name = "delete"];</code>
   * @return The count of delete.
   */
  public int getDeleteCount() {
    return delete_.size();
  }
  /**
   * <code>repeated string delete = 2 [json_name = "delete"];</code>
   * @param index The index of the element to return.
   * @return The delete at the given index.
   */
  public java.lang.String getDelete(int index) {
    return delete_.get(index);
  }
  /**
   * <code>repeated string delete = 2 [json_name = "delete"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the delete at the given index.
   */
  public com.google.protobuf.ByteString
      getDeleteBytes(int index) {
    return delete_.getByteString(index);
  }

  public static final int UPDATE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList update_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string update = 3 [json_name = "update"];</code>
   * @return A list containing the update.
   */
  public com.google.protobuf.ProtocolStringList
      getUpdateList() {
    return update_;
  }
  /**
   * <code>repeated string update = 3 [json_name = "update"];</code>
   * @return The count of update.
   */
  public int getUpdateCount() {
    return update_.size();
  }
  /**
   * <code>repeated string update = 3 [json_name = "update"];</code>
   * @param index The index of the element to return.
   * @return The update at the given index.
   */
  public java.lang.String getUpdate(int index) {
    return update_.get(index);
  }
  /**
   * <code>repeated string update = 3 [json_name = "update"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the update at the given index.
   */
  public com.google.protobuf.ByteString
      getUpdateBytes(int index) {
    return update_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < write_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, write_.getRaw(i));
    }
    for (int i = 0; i < delete_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, delete_.getRaw(i));
    }
    for (int i = 0; i < update_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, update_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < write_.size(); i++) {
        dataSize += computeStringSizeNoTag(write_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getWriteList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < delete_.size(); i++) {
        dataSize += computeStringSizeNoTag(delete_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getDeleteList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < update_.size(); i++) {
        dataSize += computeStringSizeNoTag(update_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUpdateList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.permify.grpc.Partials)) {
      return super.equals(obj);
    }
    org.permify.grpc.Partials other = (org.permify.grpc.Partials) obj;

    if (!getWriteList()
        .equals(other.getWriteList())) return false;
    if (!getDeleteList()
        .equals(other.getDeleteList())) return false;
    if (!getUpdateList()
        .equals(other.getUpdateList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getWriteCount() > 0) {
      hash = (37 * hash) + WRITE_FIELD_NUMBER;
      hash = (53 * hash) + getWriteList().hashCode();
    }
    if (getDeleteCount() > 0) {
      hash = (37 * hash) + DELETE_FIELD_NUMBER;
      hash = (53 * hash) + getDeleteList().hashCode();
    }
    if (getUpdateCount() > 0) {
      hash = (37 * hash) + UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.permify.grpc.Partials parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.Partials parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.Partials parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.Partials parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.Partials parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.Partials parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.Partials parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.Partials parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.permify.grpc.Partials parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.permify.grpc.Partials parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.permify.grpc.Partials parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.Partials parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.permify.grpc.Partials prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Partials contains the write, update and delete definitions
   * </pre>
   *
   * Protobuf type {@code base.v1.Partials}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:base.v1.Partials)
      org.permify.grpc.PartialsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.permify.grpc.BaseProto.internal_static_base_v1_Partials_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.permify.grpc.BaseProto.internal_static_base_v1_Partials_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.permify.grpc.Partials.class, org.permify.grpc.Partials.Builder.class);
    }

    // Construct using org.permify.grpc.Partials.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      write_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      delete_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      update_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.permify.grpc.BaseProto.internal_static_base_v1_Partials_descriptor;
    }

    @java.lang.Override
    public org.permify.grpc.Partials getDefaultInstanceForType() {
      return org.permify.grpc.Partials.getDefaultInstance();
    }

    @java.lang.Override
    public org.permify.grpc.Partials build() {
      org.permify.grpc.Partials result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.permify.grpc.Partials buildPartial() {
      org.permify.grpc.Partials result = new org.permify.grpc.Partials(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.permify.grpc.Partials result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        write_.makeImmutable();
        result.write_ = write_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        delete_.makeImmutable();
        result.delete_ = delete_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        update_.makeImmutable();
        result.update_ = update_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.permify.grpc.Partials) {
        return mergeFrom((org.permify.grpc.Partials)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.permify.grpc.Partials other) {
      if (other == org.permify.grpc.Partials.getDefaultInstance()) return this;
      if (!other.write_.isEmpty()) {
        if (write_.isEmpty()) {
          write_ = other.write_;
          bitField0_ |= 0x00000001;
        } else {
          ensureWriteIsMutable();
          write_.addAll(other.write_);
        }
        onChanged();
      }
      if (!other.delete_.isEmpty()) {
        if (delete_.isEmpty()) {
          delete_ = other.delete_;
          bitField0_ |= 0x00000002;
        } else {
          ensureDeleteIsMutable();
          delete_.addAll(other.delete_);
        }
        onChanged();
      }
      if (!other.update_.isEmpty()) {
        if (update_.isEmpty()) {
          update_ = other.update_;
          bitField0_ |= 0x00000004;
        } else {
          ensureUpdateIsMutable();
          update_.addAll(other.update_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureWriteIsMutable();
              write_.add(s);
              break;
            } // case 10
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureDeleteIsMutable();
              delete_.add(s);
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureUpdateIsMutable();
              update_.add(s);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList write_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureWriteIsMutable() {
      if (!write_.isModifiable()) {
        write_ = new com.google.protobuf.LazyStringArrayList(write_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @return A list containing the write.
     */
    public com.google.protobuf.ProtocolStringList
        getWriteList() {
      write_.makeImmutable();
      return write_;
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @return The count of write.
     */
    public int getWriteCount() {
      return write_.size();
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @param index The index of the element to return.
     * @return The write at the given index.
     */
    public java.lang.String getWrite(int index) {
      return write_.get(index);
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the write at the given index.
     */
    public com.google.protobuf.ByteString
        getWriteBytes(int index) {
      return write_.getByteString(index);
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @param index The index to set the value at.
     * @param value The write to set.
     * @return This builder for chaining.
     */
    public Builder setWrite(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureWriteIsMutable();
      write_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @param value The write to add.
     * @return This builder for chaining.
     */
    public Builder addWrite(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureWriteIsMutable();
      write_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @param values The write to add.
     * @return This builder for chaining.
     */
    public Builder addAllWrite(
        java.lang.Iterable<java.lang.String> values) {
      ensureWriteIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, write_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWrite() {
      write_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string write = 1 [json_name = "write"];</code>
     * @param value The bytes of the write to add.
     * @return This builder for chaining.
     */
    public Builder addWriteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureWriteIsMutable();
      write_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList delete_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureDeleteIsMutable() {
      if (!delete_.isModifiable()) {
        delete_ = new com.google.protobuf.LazyStringArrayList(delete_);
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @return A list containing the delete.
     */
    public com.google.protobuf.ProtocolStringList
        getDeleteList() {
      delete_.makeImmutable();
      return delete_;
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @return The count of delete.
     */
    public int getDeleteCount() {
      return delete_.size();
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @param index The index of the element to return.
     * @return The delete at the given index.
     */
    public java.lang.String getDelete(int index) {
      return delete_.get(index);
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the delete at the given index.
     */
    public com.google.protobuf.ByteString
        getDeleteBytes(int index) {
      return delete_.getByteString(index);
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @param index The index to set the value at.
     * @param value The delete to set.
     * @return This builder for chaining.
     */
    public Builder setDelete(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDeleteIsMutable();
      delete_.set(index, value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @param value The delete to add.
     * @return This builder for chaining.
     */
    public Builder addDelete(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureDeleteIsMutable();
      delete_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @param values The delete to add.
     * @return This builder for chaining.
     */
    public Builder addAllDelete(
        java.lang.Iterable<java.lang.String> values) {
      ensureDeleteIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, delete_);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDelete() {
      delete_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string delete = 2 [json_name = "delete"];</code>
     * @param value The bytes of the delete to add.
     * @return This builder for chaining.
     */
    public Builder addDeleteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureDeleteIsMutable();
      delete_.add(value);
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList update_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureUpdateIsMutable() {
      if (!update_.isModifiable()) {
        update_ = new com.google.protobuf.LazyStringArrayList(update_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @return A list containing the update.
     */
    public com.google.protobuf.ProtocolStringList
        getUpdateList() {
      update_.makeImmutable();
      return update_;
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @return The count of update.
     */
    public int getUpdateCount() {
      return update_.size();
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @param index The index of the element to return.
     * @return The update at the given index.
     */
    public java.lang.String getUpdate(int index) {
      return update_.get(index);
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the update at the given index.
     */
    public com.google.protobuf.ByteString
        getUpdateBytes(int index) {
      return update_.getByteString(index);
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @param index The index to set the value at.
     * @param value The update to set.
     * @return This builder for chaining.
     */
    public Builder setUpdate(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUpdateIsMutable();
      update_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @param value The update to add.
     * @return This builder for chaining.
     */
    public Builder addUpdate(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureUpdateIsMutable();
      update_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @param values The update to add.
     * @return This builder for chaining.
     */
    public Builder addAllUpdate(
        java.lang.Iterable<java.lang.String> values) {
      ensureUpdateIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, update_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdate() {
      update_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string update = 3 [json_name = "update"];</code>
     * @param value The bytes of the update to add.
     * @return This builder for chaining.
     */
    public Builder addUpdateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureUpdateIsMutable();
      update_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:base.v1.Partials)
  }

  // @@protoc_insertion_point(class_scope:base.v1.Partials)
  private static final org.permify.grpc.Partials DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.permify.grpc.Partials();
  }

  public static org.permify.grpc.Partials getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Partials>
      PARSER = new com.google.protobuf.AbstractParser<Partials>() {
    @java.lang.Override
    public Partials parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Partials> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Partials> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.permify.grpc.Partials getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

