// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base/v1/service.proto
// Protobuf Java Version: 4.27.2

package org.permify.grpc;

public interface PermissionLookupEntityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:base.v1.PermissionLookupEntityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of identifiers for entities that match the lookup.
   * </pre>
   *
   * <code>repeated string entity_ids = 1 [json_name = "entity_ids"];</code>
   * @return A list containing the entityIds.
   */
  java.util.List<java.lang.String>
      getEntityIdsList();
  /**
   * <pre>
   * List of identifiers for entities that match the lookup.
   * </pre>
   *
   * <code>repeated string entity_ids = 1 [json_name = "entity_ids"];</code>
   * @return The count of entityIds.
   */
  int getEntityIdsCount();
  /**
   * <pre>
   * List of identifiers for entities that match the lookup.
   * </pre>
   *
   * <code>repeated string entity_ids = 1 [json_name = "entity_ids"];</code>
   * @param index The index of the element to return.
   * @return The entityIds at the given index.
   */
  java.lang.String getEntityIds(int index);
  /**
   * <pre>
   * List of identifiers for entities that match the lookup.
   * </pre>
   *
   * <code>repeated string entity_ids = 1 [json_name = "entity_ids"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the entityIds at the given index.
   */
  com.google.protobuf.ByteString
      getEntityIdsBytes(int index);
}
