// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base/v1/service.proto
// Protobuf Java Version: 4.27.2

package org.permify.grpc;

/**
 * <pre>
 * RelationshipReadRequestMetadata defines the structure of the metadata for a read request focused on relationships.
 * It includes the snap_token associated with a particular state of the database.
 * </pre>
 *
 * Protobuf type {@code base.v1.RelationshipReadRequestMetadata}
 */
public final class RelationshipReadRequestMetadata extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:base.v1.RelationshipReadRequestMetadata)
    RelationshipReadRequestMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      RelationshipReadRequestMetadata.class.getName());
  }
  // Use RelationshipReadRequestMetadata.newBuilder() to construct.
  private RelationshipReadRequestMetadata(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private RelationshipReadRequestMetadata() {
    snapToken_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.permify.grpc.ServiceProto.internal_static_base_v1_RelationshipReadRequestMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.permify.grpc.ServiceProto.internal_static_base_v1_RelationshipReadRequestMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.permify.grpc.RelationshipReadRequestMetadata.class, org.permify.grpc.RelationshipReadRequestMetadata.Builder.class);
  }

  public static final int SNAP_TOKEN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object snapToken_ = "";
  /**
   * <pre>
   * snap_token represents a specific state or "snapshot" of the database.
   * </pre>
   *
   * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The snapToken.
   */
  @java.lang.Override
  public java.lang.String getSnapToken() {
    java.lang.Object ref = snapToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      snapToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * snap_token represents a specific state or "snapshot" of the database.
   * </pre>
   *
   * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
   * @return The bytes for snapToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSnapTokenBytes() {
    java.lang.Object ref = snapToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      snapToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(snapToken_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, snapToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(snapToken_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, snapToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.permify.grpc.RelationshipReadRequestMetadata)) {
      return super.equals(obj);
    }
    org.permify.grpc.RelationshipReadRequestMetadata other = (org.permify.grpc.RelationshipReadRequestMetadata) obj;

    if (!getSnapToken()
        .equals(other.getSnapToken())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SNAP_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getSnapToken().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.permify.grpc.RelationshipReadRequestMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.permify.grpc.RelationshipReadRequestMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.RelationshipReadRequestMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.permify.grpc.RelationshipReadRequestMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * RelationshipReadRequestMetadata defines the structure of the metadata for a read request focused on relationships.
   * It includes the snap_token associated with a particular state of the database.
   * </pre>
   *
   * Protobuf type {@code base.v1.RelationshipReadRequestMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:base.v1.RelationshipReadRequestMetadata)
      org.permify.grpc.RelationshipReadRequestMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_RelationshipReadRequestMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_RelationshipReadRequestMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.permify.grpc.RelationshipReadRequestMetadata.class, org.permify.grpc.RelationshipReadRequestMetadata.Builder.class);
    }

    // Construct using org.permify.grpc.RelationshipReadRequestMetadata.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      snapToken_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_RelationshipReadRequestMetadata_descriptor;
    }

    @java.lang.Override
    public org.permify.grpc.RelationshipReadRequestMetadata getDefaultInstanceForType() {
      return org.permify.grpc.RelationshipReadRequestMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public org.permify.grpc.RelationshipReadRequestMetadata build() {
      org.permify.grpc.RelationshipReadRequestMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.permify.grpc.RelationshipReadRequestMetadata buildPartial() {
      org.permify.grpc.RelationshipReadRequestMetadata result = new org.permify.grpc.RelationshipReadRequestMetadata(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.permify.grpc.RelationshipReadRequestMetadata result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.snapToken_ = snapToken_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.permify.grpc.RelationshipReadRequestMetadata) {
        return mergeFrom((org.permify.grpc.RelationshipReadRequestMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.permify.grpc.RelationshipReadRequestMetadata other) {
      if (other == org.permify.grpc.RelationshipReadRequestMetadata.getDefaultInstance()) return this;
      if (!other.getSnapToken().isEmpty()) {
        snapToken_ = other.snapToken_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              snapToken_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object snapToken_ = "";
    /**
     * <pre>
     * snap_token represents a specific state or "snapshot" of the database.
     * </pre>
     *
     * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The snapToken.
     */
    public java.lang.String getSnapToken() {
      java.lang.Object ref = snapToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        snapToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * snap_token represents a specific state or "snapshot" of the database.
     * </pre>
     *
     * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return The bytes for snapToken.
     */
    public com.google.protobuf.ByteString
        getSnapTokenBytes() {
      java.lang.Object ref = snapToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        snapToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * snap_token represents a specific state or "snapshot" of the database.
     * </pre>
     *
     * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The snapToken to set.
     * @return This builder for chaining.
     */
    public Builder setSnapToken(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      snapToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * snap_token represents a specific state or "snapshot" of the database.
     * </pre>
     *
     * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @return This builder for chaining.
     */
    public Builder clearSnapToken() {
      snapToken_ = getDefaultInstance().getSnapToken();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * snap_token represents a specific state or "snapshot" of the database.
     * </pre>
     *
     * <code>string snap_token = 1 [json_name = "snap_token", (.grpc.gateway.protoc_gen_openapiv2.options.openapiv2_field) = { ... }</code>
     * @param value The bytes for snapToken to set.
     * @return This builder for chaining.
     */
    public Builder setSnapTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      snapToken_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:base.v1.RelationshipReadRequestMetadata)
  }

  // @@protoc_insertion_point(class_scope:base.v1.RelationshipReadRequestMetadata)
  private static final org.permify.grpc.RelationshipReadRequestMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.permify.grpc.RelationshipReadRequestMetadata();
  }

  public static org.permify.grpc.RelationshipReadRequestMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RelationshipReadRequestMetadata>
      PARSER = new com.google.protobuf.AbstractParser<RelationshipReadRequestMetadata>() {
    @java.lang.Override
    public RelationshipReadRequestMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RelationshipReadRequestMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RelationshipReadRequestMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.permify.grpc.RelationshipReadRequestMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

