// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base/v1/service.proto
// Protobuf Java Version: 4.27.2

package org.permify.grpc;

/**
 * <pre>
 * SchemaReadResponse is the response message for the Read method in the Schema service.
 * It returns the requested schema.
 * </pre>
 *
 * Protobuf type {@code base.v1.SchemaReadResponse}
 */
public final class SchemaReadResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:base.v1.SchemaReadResponse)
    SchemaReadResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      SchemaReadResponse.class.getName());
  }
  // Use SchemaReadResponse.newBuilder() to construct.
  private SchemaReadResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SchemaReadResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.permify.grpc.ServiceProto.internal_static_base_v1_SchemaReadResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.permify.grpc.ServiceProto.internal_static_base_v1_SchemaReadResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.permify.grpc.SchemaReadResponse.class, org.permify.grpc.SchemaReadResponse.Builder.class);
  }

  private int bitField0_;
  public static final int SCHEMA_FIELD_NUMBER = 1;
  private org.permify.grpc.SchemaDefinition schema_;
  /**
   * <pre>
   * schema is the SchemaDefinition that represents the read schema.
   * </pre>
   *
   * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
   * @return Whether the schema field is set.
   */
  @java.lang.Override
  public boolean hasSchema() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * schema is the SchemaDefinition that represents the read schema.
   * </pre>
   *
   * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
   * @return The schema.
   */
  @java.lang.Override
  public org.permify.grpc.SchemaDefinition getSchema() {
    return schema_ == null ? org.permify.grpc.SchemaDefinition.getDefaultInstance() : schema_;
  }
  /**
   * <pre>
   * schema is the SchemaDefinition that represents the read schema.
   * </pre>
   *
   * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
   */
  @java.lang.Override
  public org.permify.grpc.SchemaDefinitionOrBuilder getSchemaOrBuilder() {
    return schema_ == null ? org.permify.grpc.SchemaDefinition.getDefaultInstance() : schema_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getSchema());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSchema());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.permify.grpc.SchemaReadResponse)) {
      return super.equals(obj);
    }
    org.permify.grpc.SchemaReadResponse other = (org.permify.grpc.SchemaReadResponse) obj;

    if (hasSchema() != other.hasSchema()) return false;
    if (hasSchema()) {
      if (!getSchema()
          .equals(other.getSchema())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSchema()) {
      hash = (37 * hash) + SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getSchema().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.permify.grpc.SchemaReadResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.permify.grpc.SchemaReadResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.permify.grpc.SchemaReadResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.permify.grpc.SchemaReadResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.permify.grpc.SchemaReadResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * SchemaReadResponse is the response message for the Read method in the Schema service.
   * It returns the requested schema.
   * </pre>
   *
   * Protobuf type {@code base.v1.SchemaReadResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:base.v1.SchemaReadResponse)
      org.permify.grpc.SchemaReadResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_SchemaReadResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_SchemaReadResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.permify.grpc.SchemaReadResponse.class, org.permify.grpc.SchemaReadResponse.Builder.class);
    }

    // Construct using org.permify.grpc.SchemaReadResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getSchemaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.permify.grpc.ServiceProto.internal_static_base_v1_SchemaReadResponse_descriptor;
    }

    @java.lang.Override
    public org.permify.grpc.SchemaReadResponse getDefaultInstanceForType() {
      return org.permify.grpc.SchemaReadResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.permify.grpc.SchemaReadResponse build() {
      org.permify.grpc.SchemaReadResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.permify.grpc.SchemaReadResponse buildPartial() {
      org.permify.grpc.SchemaReadResponse result = new org.permify.grpc.SchemaReadResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.permify.grpc.SchemaReadResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schema_ = schemaBuilder_ == null
            ? schema_
            : schemaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.permify.grpc.SchemaReadResponse) {
        return mergeFrom((org.permify.grpc.SchemaReadResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.permify.grpc.SchemaReadResponse other) {
      if (other == org.permify.grpc.SchemaReadResponse.getDefaultInstance()) return this;
      if (other.hasSchema()) {
        mergeSchema(other.getSchema());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getSchemaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.permify.grpc.SchemaDefinition schema_;
    private com.google.protobuf.SingleFieldBuilder<
        org.permify.grpc.SchemaDefinition, org.permify.grpc.SchemaDefinition.Builder, org.permify.grpc.SchemaDefinitionOrBuilder> schemaBuilder_;
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     * @return Whether the schema field is set.
     */
    public boolean hasSchema() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     * @return The schema.
     */
    public org.permify.grpc.SchemaDefinition getSchema() {
      if (schemaBuilder_ == null) {
        return schema_ == null ? org.permify.grpc.SchemaDefinition.getDefaultInstance() : schema_;
      } else {
        return schemaBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    public Builder setSchema(org.permify.grpc.SchemaDefinition value) {
      if (schemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        schema_ = value;
      } else {
        schemaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    public Builder setSchema(
        org.permify.grpc.SchemaDefinition.Builder builderForValue) {
      if (schemaBuilder_ == null) {
        schema_ = builderForValue.build();
      } else {
        schemaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    public Builder mergeSchema(org.permify.grpc.SchemaDefinition value) {
      if (schemaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          schema_ != null &&
          schema_ != org.permify.grpc.SchemaDefinition.getDefaultInstance()) {
          getSchemaBuilder().mergeFrom(value);
        } else {
          schema_ = value;
        }
      } else {
        schemaBuilder_.mergeFrom(value);
      }
      if (schema_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    public Builder clearSchema() {
      bitField0_ = (bitField0_ & ~0x00000001);
      schema_ = null;
      if (schemaBuilder_ != null) {
        schemaBuilder_.dispose();
        schemaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    public org.permify.grpc.SchemaDefinition.Builder getSchemaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getSchemaFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    public org.permify.grpc.SchemaDefinitionOrBuilder getSchemaOrBuilder() {
      if (schemaBuilder_ != null) {
        return schemaBuilder_.getMessageOrBuilder();
      } else {
        return schema_ == null ?
            org.permify.grpc.SchemaDefinition.getDefaultInstance() : schema_;
      }
    }
    /**
     * <pre>
     * schema is the SchemaDefinition that represents the read schema.
     * </pre>
     *
     * <code>.base.v1.SchemaDefinition schema = 1 [json_name = "schema"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.permify.grpc.SchemaDefinition, org.permify.grpc.SchemaDefinition.Builder, org.permify.grpc.SchemaDefinitionOrBuilder> 
        getSchemaFieldBuilder() {
      if (schemaBuilder_ == null) {
        schemaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.permify.grpc.SchemaDefinition, org.permify.grpc.SchemaDefinition.Builder, org.permify.grpc.SchemaDefinitionOrBuilder>(
                getSchema(),
                getParentForChildren(),
                isClean());
        schema_ = null;
      }
      return schemaBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:base.v1.SchemaReadResponse)
  }

  // @@protoc_insertion_point(class_scope:base.v1.SchemaReadResponse)
  private static final org.permify.grpc.SchemaReadResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.permify.grpc.SchemaReadResponse();
  }

  public static org.permify.grpc.SchemaReadResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SchemaReadResponse>
      PARSER = new com.google.protobuf.AbstractParser<SchemaReadResponse>() {
    @java.lang.Override
    public SchemaReadResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SchemaReadResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SchemaReadResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.permify.grpc.SchemaReadResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

