// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base/v1/service.proto
// Protobuf Java Version: 4.27.2

package org.permify.grpc;

public interface SchemaListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:base.v1.SchemaListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * head of the schemas is the latest version available for the tenant
   * </pre>
   *
   * <code>string head = 1 [json_name = "head"];</code>
   * @return The head.
   */
  java.lang.String getHead();
  /**
   * <pre>
   * head of the schemas is the latest version available for the tenant
   * </pre>
   *
   * <code>string head = 1 [json_name = "head"];</code>
   * @return The bytes for head.
   */
  com.google.protobuf.ByteString
      getHeadBytes();

  /**
   * <pre>
   * list of schema versions with creation timestamps
   * </pre>
   *
   * <code>repeated .base.v1.SchemaList schemas = 2 [json_name = "schemas"];</code>
   */
  java.util.List<org.permify.grpc.SchemaList> 
      getSchemasList();
  /**
   * <pre>
   * list of schema versions with creation timestamps
   * </pre>
   *
   * <code>repeated .base.v1.SchemaList schemas = 2 [json_name = "schemas"];</code>
   */
  org.permify.grpc.SchemaList getSchemas(int index);
  /**
   * <pre>
   * list of schema versions with creation timestamps
   * </pre>
   *
   * <code>repeated .base.v1.SchemaList schemas = 2 [json_name = "schemas"];</code>
   */
  int getSchemasCount();
  /**
   * <pre>
   * list of schema versions with creation timestamps
   * </pre>
   *
   * <code>repeated .base.v1.SchemaList schemas = 2 [json_name = "schemas"];</code>
   */
  java.util.List<? extends org.permify.grpc.SchemaListOrBuilder> 
      getSchemasOrBuilderList();
  /**
   * <pre>
   * list of schema versions with creation timestamps
   * </pre>
   *
   * <code>repeated .base.v1.SchemaList schemas = 2 [json_name = "schemas"];</code>
   */
  org.permify.grpc.SchemaListOrBuilder getSchemasOrBuilder(
      int index);

  /**
   * <pre>
   * continuous_token is a string that can be used to paginate and retrieve the next set of results.
   * </pre>
   *
   * <code>string continuous_token = 3 [json_name = "continuous_token"];</code>
   * @return The continuousToken.
   */
  java.lang.String getContinuousToken();
  /**
   * <pre>
   * continuous_token is a string that can be used to paginate and retrieve the next set of results.
   * </pre>
   *
   * <code>string continuous_token = 3 [json_name = "continuous_token"];</code>
   * @return The bytes for continuousToken.
   */
  com.google.protobuf.ByteString
      getContinuousTokenBytes();
}
