/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.4.2
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import co.permify.sdk.model.V1alpha1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Function type with result and arg types.
 */
@JsonPropertyOrder({
  FunctionType.JSON_PROPERTY_RESULT_TYPE,
  FunctionType.JSON_PROPERTY_ARG_TYPES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class FunctionType {
  public static final String JSON_PROPERTY_RESULT_TYPE = "resultType";
  private V1alpha1Type resultType;

  public static final String JSON_PROPERTY_ARG_TYPES = "argTypes";
  private List<V1alpha1Type> argTypes;

  public FunctionType() { 
  }

  public FunctionType resultType(V1alpha1Type resultType) {
    this.resultType = resultType;
    return this;
  }

   /**
   * Get resultType
   * @return resultType
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESULT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public V1alpha1Type getResultType() {
    return resultType;
  }


  @JsonProperty(JSON_PROPERTY_RESULT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResultType(V1alpha1Type resultType) {
    this.resultType = resultType;
  }


  public FunctionType argTypes(List<V1alpha1Type> argTypes) {
    this.argTypes = argTypes;
    return this;
  }

  public FunctionType addArgTypesItem(V1alpha1Type argTypesItem) {
    if (this.argTypes == null) {
      this.argTypes = new ArrayList<>();
    }
    this.argTypes.add(argTypesItem);
    return this;
  }

   /**
   * Argument types of the function.
   * @return argTypes
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARG_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<V1alpha1Type> getArgTypes() {
    return argTypes;
  }


  @JsonProperty(JSON_PROPERTY_ARG_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArgTypes(List<V1alpha1Type> argTypes) {
    this.argTypes = argTypes;
  }


  /**
   * Return true if this FunctionType object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FunctionType functionType = (FunctionType) o;
    return Objects.equals(this.resultType, functionType.resultType) &&
        Objects.equals(this.argTypes, functionType.argTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resultType, argTypes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FunctionType {\n");
    sb.append("    resultType: ").append(toIndentedString(resultType)).append("\n");
    sb.append("    argTypes: ").append(toIndentedString(argTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `resultType` to the URL query string
    if (getResultType() != null) {
      joiner.add(getResultType().toUrlQueryString(prefix + "resultType" + suffix));
    }

    // add `argTypes` to the URL query string
    if (getArgTypes() != null) {
      for (int i = 0; i < getArgTypes().size(); i++) {
        if (getArgTypes().get(i) != null) {
          joiner.add(getArgTypes().get(i).toUrlQueryString(String.format("%sargTypes%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

