/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.0.3
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import co.permify.sdk.client.ApiClient;
/**
 * PermissionLookupEntityResponse is the response message for the LookupEntity method in the Permission service.
 */
@JsonPropertyOrder({
  PermissionLookupEntityResponse.JSON_PROPERTY_ENTITY_IDS,
  PermissionLookupEntityResponse.JSON_PROPERTY_CONTINUOUS_TOKEN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PermissionLookupEntityResponse {
  public static final String JSON_PROPERTY_ENTITY_IDS = "entity_ids";
  @jakarta.annotation.Nullable
  private List<String> entityIds = new ArrayList<>();

  public static final String JSON_PROPERTY_CONTINUOUS_TOKEN = "continuous_token";
  @jakarta.annotation.Nullable
  private String continuousToken;

  public PermissionLookupEntityResponse() { 
  }

  public PermissionLookupEntityResponse entityIds(@jakarta.annotation.Nullable List<String> entityIds) {
    this.entityIds = entityIds;
    return this;
  }

  public PermissionLookupEntityResponse addEntityIdsItem(String entityIdsItem) {
    if (this.entityIds == null) {
      this.entityIds = new ArrayList<>();
    }
    this.entityIds.add(entityIdsItem);
    return this;
  }

  /**
   * List of identifiers for entities that match the lookup.
   * @return entityIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getEntityIds() {
    return entityIds;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityIds(@jakarta.annotation.Nullable List<String> entityIds) {
    this.entityIds = entityIds;
  }


  public PermissionLookupEntityResponse continuousToken(@jakarta.annotation.Nullable String continuousToken) {
    this.continuousToken = continuousToken;
    return this;
  }

  /**
   * continuous_token is a string that can be used to paginate and retrieve the next set of results.
   * @return continuousToken
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONTINUOUS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContinuousToken() {
    return continuousToken;
  }


  @JsonProperty(JSON_PROPERTY_CONTINUOUS_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContinuousToken(@jakarta.annotation.Nullable String continuousToken) {
    this.continuousToken = continuousToken;
  }


  /**
   * Return true if this PermissionLookupEntityResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PermissionLookupEntityResponse permissionLookupEntityResponse = (PermissionLookupEntityResponse) o;
    return Objects.equals(this.entityIds, permissionLookupEntityResponse.entityIds) &&
        Objects.equals(this.continuousToken, permissionLookupEntityResponse.continuousToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityIds, continuousToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PermissionLookupEntityResponse {\n");
    sb.append("    entityIds: ").append(toIndentedString(entityIds)).append("\n");
    sb.append("    continuousToken: ").append(toIndentedString(continuousToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `entity_ids` to the URL query string
    if (getEntityIds() != null) {
      for (int i = 0; i < getEntityIds().size(); i++) {
        joiner.add(String.format("%sentity_ids%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getEntityIds().get(i)))));
      }
    }

    // add `continuous_token` to the URL query string
    if (getContinuousToken() != null) {
      joiner.add(String.format("%scontinuous_token%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContinuousToken()))));
    }

    return joiner.toString();
  }
}

