/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.0.3
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import co.permify.sdk.model.ComputedUserSet;
import co.permify.sdk.model.TupleSet;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import co.permify.sdk.client.ApiClient;
/**
 * TupleToUserSet defines a mapping from tuple sets to computed user sets.
 */
@JsonPropertyOrder({
  TupleToUserSet.JSON_PROPERTY_TUPLE_SET,
  TupleToUserSet.JSON_PROPERTY_COMPUTED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TupleToUserSet {
  public static final String JSON_PROPERTY_TUPLE_SET = "tupleSet";
  @jakarta.annotation.Nullable
  private TupleSet tupleSet;

  public static final String JSON_PROPERTY_COMPUTED = "computed";
  @jakarta.annotation.Nullable
  private ComputedUserSet computed;

  public TupleToUserSet() { 
  }

  public TupleToUserSet tupleSet(@jakarta.annotation.Nullable TupleSet tupleSet) {
    this.tupleSet = tupleSet;
    return this;
  }

  /**
   * Get tupleSet
   * @return tupleSet
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TUPLE_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TupleSet getTupleSet() {
    return tupleSet;
  }


  @JsonProperty(JSON_PROPERTY_TUPLE_SET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTupleSet(@jakarta.annotation.Nullable TupleSet tupleSet) {
    this.tupleSet = tupleSet;
  }


  public TupleToUserSet computed(@jakarta.annotation.Nullable ComputedUserSet computed) {
    this.computed = computed;
    return this;
  }

  /**
   * Get computed
   * @return computed
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ComputedUserSet getComputed() {
    return computed;
  }


  @JsonProperty(JSON_PROPERTY_COMPUTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComputed(@jakarta.annotation.Nullable ComputedUserSet computed) {
    this.computed = computed;
  }


  /**
   * Return true if this TupleToUserSet object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TupleToUserSet tupleToUserSet = (TupleToUserSet) o;
    return Objects.equals(this.tupleSet, tupleToUserSet.tupleSet) &&
        Objects.equals(this.computed, tupleToUserSet.computed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tupleSet, computed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TupleToUserSet {\n");
    sb.append("    tupleSet: ").append(toIndentedString(tupleSet)).append("\n");
    sb.append("    computed: ").append(toIndentedString(computed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tupleSet` to the URL query string
    if (getTupleSet() != null) {
      joiner.add(getTupleSet().toUrlQueryString(prefix + "tupleSet" + suffix));
    }

    // add `computed` to the URL query string
    if (getComputed() != null) {
      joiner.add(getComputed().toUrlQueryString(prefix + "computed" + suffix));
    }

    return joiner.toString();
  }
}

