/*
 * Permify API
 * Permify is an open source authorization service for creating fine-grained and scalable authorization systems.
 *
 * The version of the OpenAPI document: v1.4.4
 * Contact: hello@permify.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package co.permify.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import co.permify.sdk.model.RelationshipWriteRequestMetadata;
import co.permify.sdk.model.Tuple;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Represents a request to write relationship data.
 */
@JsonPropertyOrder({
  WriteRelationshipsBody.JSON_PROPERTY_METADATA,
  WriteRelationshipsBody.JSON_PROPERTY_TUPLES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class WriteRelationshipsBody {
  public static final String JSON_PROPERTY_METADATA = "metadata";
  private RelationshipWriteRequestMetadata metadata;

  public static final String JSON_PROPERTY_TUPLES = "tuples";
  private List<Tuple> tuples;

  public WriteRelationshipsBody() { 
  }

  public WriteRelationshipsBody metadata(RelationshipWriteRequestMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RelationshipWriteRequestMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(RelationshipWriteRequestMetadata metadata) {
    this.metadata = metadata;
  }


  public WriteRelationshipsBody tuples(List<Tuple> tuples) {
    this.tuples = tuples;
    return this;
  }

  public WriteRelationshipsBody addTuplesItem(Tuple tuplesItem) {
    if (this.tuples == null) {
      this.tuples = new ArrayList<>();
    }
    this.tuples.add(tuplesItem);
    return this;
  }

   /**
   * List of tuples for the request. Must have between 1 and 100 items.
   * @return tuples
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TUPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Tuple> getTuples() {
    return tuples;
  }


  @JsonProperty(JSON_PROPERTY_TUPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTuples(List<Tuple> tuples) {
    this.tuples = tuples;
  }


  /**
   * Return true if this WriteRelationshipsBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WriteRelationshipsBody writeRelationshipsBody = (WriteRelationshipsBody) o;
    return Objects.equals(this.metadata, writeRelationshipsBody.metadata) &&
        Objects.equals(this.tuples, writeRelationshipsBody.tuples);
  }

  @Override
  public int hashCode() {
    return Objects.hash(metadata, tuples);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WriteRelationshipsBody {\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    tuples: ").append(toIndentedString(tuples)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(getMetadata().toUrlQueryString(prefix + "metadata" + suffix));
    }

    // add `tuples` to the URL query string
    if (getTuples() != null) {
      for (int i = 0; i < getTuples().size(); i++) {
        if (getTuples().get(i) != null) {
          joiner.add(getTuples().get(i).toUrlQueryString(String.format("%stuples%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

